//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VYT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileStorage
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public int Type { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string Description { get; set; }
        public string FilePath { get; set; }
        public string FileType { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
