//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VYT.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VYT_TTKTEntities : DbContext
    {
        public VYT_TTKTEntities()
            : base("name=VYT_TTKTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FileStorage> FileStorages { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobLog> JobLogs { get; set; }
    }
}
